# Generated by Django 4.2 on 2025-07-07 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100, verbose_name='主机名')),
                ('ip_address', models.CharField(max_length=100, verbose_name='IP地址')),
                ('port', models.IntegerField(default=22, verbose_name='SSH端口')),
                ('os_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='操作系统类型')),
                ('os_version', models.CharField(blank=True, max_length=50, null=True, verbose_name='操作系统版本')),
                ('status', models.CharField(choices=[('online', '在线'), ('offline', '离线'), ('unknown', '未知'), ('maintenance', '维护中')], default='unknown', max_length=20, verbose_name='状态')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '主机',
                'verbose_name_plural': '主机',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SSHCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='凭证名称')),
                ('auth_type', models.CharField(choices=[('password', '密码'), ('key', '密钥')], default='password', max_length=20, verbose_name='认证类型')),
                ('username', models.CharField(max_length=100, verbose_name='用户名')),
                ('password', models.CharField(blank=True, max_length=255, null=True, verbose_name='密码')),
                ('private_key', models.TextField(blank=True, null=True, verbose_name='私钥')),
                ('passphrase', models.CharField(blank=True, max_length=255, null=True, verbose_name='密钥口令')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('hosts', models.ManyToManyField(blank=True, related_name='credentials', to='hosts.host', verbose_name='关联主机')),
            ],
            options={
                'verbose_name': 'SSH凭证',
                'verbose_name_plural': 'SSH凭证',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HostTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名')),
                ('color', models.CharField(default='#1890ff', max_length=20, verbose_name='标签颜色')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('hosts', models.ManyToManyField(blank=True, related_name='tags', to='hosts.host', verbose_name='关联主机')),
            ],
            options={
                'verbose_name': '主机标签',
                'verbose_name_plural': '主机标签',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='组名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '主机组',
                'verbose_name_plural': '主机组',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='host',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='hosts', to='hosts.hostgroup', verbose_name='所属组'),
        ),
        migrations.AlterUniqueTogether(
            name='host',
            unique_together={('hostname', 'ip_address')},
        ),
    ]
