# Generated by Django 4.2 on 2025-06-17 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='任务名称')),
                ('description', models.TextField(blank=True, verbose_name='任务描述')),
                ('command', models.TextField(verbose_name='执行命令')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='命令参数')),
                ('environment_variables', models.JSONField(blank=True, default=dict, verbose_name='环境变量')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '运行中'), ('success', '成功'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('is_scheduled', models.BooleanField(default=False, verbose_name='是否定时任务')),
                ('schedule', models.CharField(blank=True, help_text='Cron表达式，如: 0 0 * * *', max_length=100, verbose_name='定时计划')),
                ('timeout', models.IntegerField(default=1800, verbose_name='超时时间(秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_build_tasks', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_tasks', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '构建任务',
                'verbose_name_plural': '构建任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BuildHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_number', models.IntegerField(verbose_name='构建编号')),
                ('status', models.CharField(choices=[('running', '运行中'), ('success', '成功'), ('failed', '失败'), ('cancelled', '已取消')], default='running', max_length=20, verbose_name='状态')),
                ('execution_path', models.CharField(blank=True, max_length=255, verbose_name='执行路径')),
                ('log_file', models.CharField(blank=True, max_length=255, verbose_name='日志文件')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('duration', models.IntegerField(default=0, verbose_name='持续时间(秒)')),
                ('executed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_builds', to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_histories', to='builds.buildtask', verbose_name='所属任务')),
            ],
            options={
                'verbose_name': '构建历史',
                'verbose_name_plural': '构建历史',
                'ordering': ['-started_at'],
                'unique_together': {('task', 'build_number')},
            },
        ),
    ]
