# Generated by Django 4.2 on 2025-06-17 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='凭据名称')),
                ('credential_type', models.CharField(choices=[('ssh_key', 'SSH密钥'), ('username_password', '用户名密码'), ('api_key', 'API密钥'), ('token', '访问令牌'), ('certificate', '证书'), ('other', '其他')], max_length=20, verbose_name='凭据类型')),
                ('description', models.TextField(blank=True, verbose_name='凭据描述')),
                ('username', models.CharField(blank=True, max_length=100, verbose_name='用户名')),
                ('password', models.TextField(blank=True, verbose_name='密码')),
                ('private_key', models.TextField(blank=True, verbose_name='私钥')),
                ('key_passphrase', models.TextField(blank=True, verbose_name='密钥口令')),
                ('token', models.TextField(blank=True, verbose_name='令牌')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='额外数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '凭据',
                'verbose_name_plural': '凭据',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CredentialUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, max_length=50, verbose_name='IP地址')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='使用时间')),
                ('action', models.CharField(blank=True, max_length=100, verbose_name='操作')),
                ('task_info', models.JSONField(blank=True, default=dict, verbose_name='任务信息')),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='credentials.credential', verbose_name='凭据')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credential_usages', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '凭据使用日志',
                'verbose_name_plural': '凭据使用日志',
                'ordering': ['-used_at'],
            },
        ),
    ]
